version: 2
jobs:
  rust/coverage:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: Show CPU info
          command: |
            nproc
            lscpu
      - run:
          name: Run cargo tarpaulin (Allowing a failure)
          command: |
            docker run --security-opt seccomp=unconfined -v "${PWD}:/volume" \
              --env RUSTFLAGS='--cfg circleci' \
              xd009642/tarpaulin \
              cargo tarpaulin -v \
                --features 'sync, future' \
                --ciserver circle-ci \
                --coveralls ${COVERALLS_TOKEN} \
                --timeout 600 \
            || true

workflows:
  build:
    jobs:
    - rust/coverage:
        filters:
          # Ignore pushes on temporary branches for GitHub merge queue.
          branches:
            ignore: /gh-readonly-queue\/.*/
  version: 2
